_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.10
            "5": 0.18.6
            "6": 4.44.1
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 4
disable_wandb:
    value: false
gradient_accumulation_steps:
    value: 4
group_size:
    value: 8
hist_path:
    value: /path/to/histograms
learning_rate:
    value: 2e-05
max_length:
    value: 512
model_name:
    value: /home/riyasatohib_cohere_com/repos/models/meta-llama/Meta-Llama-3-8B
num_epochs:
    value: 3
output_dir:
    value: ./sparse_finetuned
reg_types:
    value:
        - l1
        - hoyer
reg_weights:
    value:
        - 0.01
        - 0.005
threshold:
    value: 0.1
wandb_project:
    value: sparse-llama-finetune
warmup_steps:
    value: 100
