_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.6
            "6": 4.44.1
            "8":
                - 5
                - 9
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 4
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 2e-05
max_length:
    value: 512
model_path:
    value: /home/riyasatohib_cohere_com/repos/models/meta-llama/Meta-Llama-3-8B
num_epochs:
    value: 3
output_dir:
    value: ./output-mod
reg_types:
    value:
        - l1
        - hoyer
reg_weights:
    value:
        - 0.01
        - 0.01
wandb_project:
    value: llama-activation-regularization
warmup_steps:
    value: 100
